#!/usr/bin/python
import serial, os, time

def listToString(nmeaParsed):
	string = "".join(nmeaParsed)
	return string

i = 0
northSouth = []
eastWest = []
utcTime = []
latitude = []
longitude = []
compare = []
str1 = ''

ser = serial.Serial(
	port='/dev/ttyAMA0',
	baudrate = 9600,
	parity = serial.PARITY_NONE,
	stopbits = serial.STOPBITS_ONE,
	bytesize = serial.EIGHTBITS,
	timeout = 1
	)	

#ff = open("nmea.txt", "a")
time.sleep(1)
for i in range(100):
	x = ser.readline()
	print(x)
	parse = x.split(",")
#	print(x)
	if (parse[0] == '$GPRMC'):
		latitude = listToString(parse[3])
#		print(parse[3])
#		print(latitude)
#print(x)
#print(utcTime)
#print(utcTime[5])
#ff.close()
